# permissions for end users to edit auditloggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: auditlogger-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: auditlogger
    app.kubernetes.io/part-of: auditlogger
    app.kubernetes.io/managed-by: kustomize
  name: auditlogger-editor-role
rules:
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - auditloggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.spark.co.nz
  resources:
  - auditloggers/status
  verbs:
  - get
