//go:build !ignore_autogenerated

/*
Copyright 2024 baranitharan.chittharanjan@spark.co.nz.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogger) DeepCopyInto(out *AuditLogger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogger.
func (in *AuditLogger) DeepCopy() *AuditLogger {
	if in == nil {
		return nil
	}
	out := new(AuditLogger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditLogger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLoggerList) DeepCopyInto(out *AuditLoggerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuditLogger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLoggerList.
func (in *AuditLoggerList) DeepCopy() *AuditLoggerList {
	if in == nil {
		return nil
	}
	out := new(AuditLoggerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditLoggerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLoggerSpec) DeepCopyInto(out *AuditLoggerSpec) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(string)
		**out = **in
	}
	in.DbInfo.DeepCopyInto(&out.DbInfo)
	in.PodInfo.DeepCopyInto(&out.PodInfo)
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	if in.SuspendEmailAlert != nil {
		in, out := &in.SuspendEmailAlert, &out.SuspendEmailAlert
		*out = new(bool)
		**out = **in
	}
	if in.NotifyExternal != nil {
		in, out := &in.NotifyExternal, &out.NotifyExternal
		*out = new(bool)
		**out = **in
	}
	if in.SyncInterval != nil {
		in, out := &in.SyncInterval, &out.SyncInterval
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLoggerSpec.
func (in *AuditLoggerSpec) DeepCopy() *AuditLoggerSpec {
	if in == nil {
		return nil
	}
	out := new(AuditLoggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLoggerStatus) DeepCopyInto(out *AuditLoggerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.IncidentID != nil {
		in, out := &in.IncidentID, &out.IncidentID
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedChecks != nil {
		in, out := &in.FailedChecks, &out.FailedChecks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSuccessfulRunTime != nil {
		in, out := &in.LastSuccessfulRunTime, &out.LastSuccessfulRunTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLoggerStatus.
func (in *AuditLoggerStatus) DeepCopy() *AuditLoggerStatus {
	if in == nil {
		return nil
	}
	out := new(AuditLoggerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBInfo) DeepCopyInto(out *DBInfo) {
	*out = *in
	if in.DatabaseSvcName != nil {
		in, out := &in.DatabaseSvcName, &out.DatabaseSvcName
		*out = new(string)
		**out = **in
	}
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.MaxOpenConn != nil {
		in, out := &in.MaxOpenConn, &out.MaxOpenConn
		*out = new(int64)
		**out = **in
	}
	if in.MaxIdleConn != nil {
		in, out := &in.MaxIdleConn, &out.MaxIdleConn
		*out = new(int64)
		**out = **in
	}
	if in.MaxIdleTime != nil {
		in, out := &in.MaxIdleTime, &out.MaxIdleTime
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBInfo.
func (in *DBInfo) DeepCopy() *DBInfo {
	if in == nil {
		return nil
	}
	out := new(DBInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodInfo) DeepCopyInto(out *PodInfo) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodInfo.
func (in *PodInfo) DeepCopy() *PodInfo {
	if in == nil {
		return nil
	}
	out := new(PodInfo)
	in.DeepCopyInto(out)
	return out
}
